/* Subsets the fonts in fonts-src/ down to the characters the site can render,
   writing the results into public/fonts/.
 *
 * Run by hand, not at build time: the output is committed, so a deploy never
 * needs Python or fontTools. Re-run it if the copy ever needs a character the
 * subset does not carry, then commit what changes.
 *
 *   pip install fonttools brotli
 *   node scripts/subset-fonts.mjs
 *
 * The charset is deliberately wider than what the site uses today: all of
 * basic Latin and Latin-1 plus common typography, so an accent or a curly
 * quote in new copy cannot silently fall back to a system font.
 */
import { execFileSync } from "node:child_process"
import { readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs"
import { join } from "node:path"

const SRC = "fonts-src"
const OUT = "public/fonts"

const ranges = [
  [0x20, 0x7e], // basic Latin
  [0xa0, 0xff], // Latin-1 supplement: accented characters
]
const extra = "‘’“”„†‡•…‰′″‹›⁄€™®©°±×÷≈≠≤≥→←↑↓–—"

const codes = new Set()
for (const [a, b] of ranges) for (let c = a; c <= b; c++) codes.add(c)
for (const ch of extra) codes.add(ch.codePointAt(0))
const unicodes = [...codes].sort((a, b) => a - b).map((c) => `U+${c.toString(16).toUpperCase().padStart(4, "0")}`).join(",")

mkdirSync(OUT, { recursive: true })
let before = 0
let after = 0
const rows = []

for (const file of readdirSync(SRC).filter((f) => f.endsWith(".woff2")).sort()) {
  const src = join(SRC, file)
  const dst = join(OUT, file)
  execFileSync("pyftsubset", [
    src,
    `--output-file=${dst}`,
    "--flavor=woff2",
    `--unicodes=${unicodes}`,
    "--layout-features=kern,liga,calt,onum,lnum",
    "--no-hinting",
    "--desubroutinize",
  ])
  const b = statSync(src).size
  const a = statSync(dst).size
  before += b
  after += a
  rows.push({ file, before: b, after: a })
}

const kb = (n) => `${Math.round(n / 1024)} KB`
for (const r of rows) {
  console.log(`  ${r.file.padEnd(38)} ${kb(r.before).padStart(7)} -> ${kb(r.after).padStart(6)}   -${Math.round(100 * (1 - r.after / r.before))}%`)
}
console.log(`\n  total ${kb(before)} -> ${kb(after)}   saving ${kb(before - after)} (${Math.round(100 * (1 - after / before))}%)`)

writeFileSync(
  join(OUT, "SUBSET.md"),
  `These files are subsets, generated by scripts/subset-fonts.mjs from fonts-src/.\n\n` +
    `Do not edit them and do not replace them with full fonts: that is ${kb(before - after)} of\n` +
    `download on every first visit. The originals live in fonts-src/ and are not\n` +
    `published.\n\n` +
    `Charset: basic Latin, Latin-1 supplement, and common typography. If copy ever\n` +
    `needs a character outside that, widen the range in the script and re-run it.\n\n` +
    `Last run: ${kb(before)} -> ${kb(after)}.\n`
)
